### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by satishtiwari23** [zeerorg/cron-connector#10]
Hi @zeerorg, @alexellis 
Please see the function configuration and other details in below given repository,
https://github.com/satishtiwari23/openfaas.git

In order to reproduce, just create, build and deploy the hello-world template.

There are 2 issues:
1) cron connector is crashing with below mentioned error at the time execution( function is being run continuously even after error)
2) if we schedule 2 functions, both are being added to cron connector but second is being run twice and failed immediately with same error. 

After deploying 'hello-world-1' function, function is being added in cron-connctor and run on schedule time, but failing imeediately with below error:
2019/05/22 15:34:51 added function hello-world-1
2019/05/22 15:36:00 Executed function: hello-world-1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x606ae8]

goroutine 55 [running]:
github.com/zeerorg/cron-connector/types.CronFunction.InvokeFunction(0xc420060360, 0xc42006a770, 0xd, 0xc42006a7d0, 0xb, 0xc420062d80, 0x0, 0x0, 0x0)
	/go/src/github.com/zeerorg/cron-connector/types/cron_function.go:105 +0x2d8
github.com/zeerorg/cron-connector/types.(*Scheduler).AddCronFunction.func1()
	/go/src/github.com/zeerorg/cron-connector/types/scheduler.go:39 +0x15b
github.com/zeerorg/cron-connector/vendor/gopkg.in/robfig/cron%2ev2.FuncJob.Run(0xc4200ea9c0)
	/go/src/github.com/zeerorg/cron-connector/vendor/gopkg.in/robfig/cron.v2/cron.go:94 +0x25
created by github.com/zeerorg/cron-connector/vendor/gopkg.in/robfig/cron%2ev2.(*Cron).run
	/go/src/github.com/zeerorg/cron-connector/vendor/gopkg.in/robfig/cron.v2/cron.go:189 +0x2ab

**Comment by zeerorg** [comment]
I'll look into this and try to reproduce this.

**Comment by zeerorg** [comment]
I wasn't able to reproduce issue. The function worked well on my machine. Can you provide more info on your setup ? Example the provider (docker or kubernetes) and the services that are running alongside by doing (`docker service ls` / `kubectl get pods --all-namespaces` )

the logs on my machine: 
![image](https://user-images.githubusercontent.com/13547997/58306613-a809af80-7e19-11e9-84f8-82bafefdb5fe.png)

**Comment by satishtiwari23** [comment]
So here is more information on setup. I have docker install on windows machine.
Here is docker info along with services
![image](https://user-images.githubusercontent.com/12987391/58335548-cec2e880-7e0f-11e9-9c75-7a47e6ac92af.png)

**DOCKER- INFO**
Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 413
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 
 Is Manager: true
 ClusterID: 
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 
 Manager Addresses:
  
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d374107
ID: X5A6:UTON:XN5Z:NYQB:AUIB:PAIR:PGYH:XTI2:I4GV:FVAG:A4SH:23MH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 148
 Goroutines: 436
 System Time: 2019-05-24T14:30:20.7078803Z
 EventsListeners: 13
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by satishtiwari23** [comment]
@zeerorg  are you able to reproduce the issue? Is there any fix for it.

**Comment by zeerorg** [comment]
I haven't been able to reproduce this issue. Are there any things that are specific to your openfaas deployment that I should take into account ?

**Comment by zeerorg** [comment]
I tried deploying the function today and was able to replicate the issue. I'll look what is causing this and will get back here.

**Comment by zeerorg** [comment]
@satishtiwari23  Thanks for filing the issue it has been fixed in the latest release and yaml files have been updated. I urge you to give it a try and report back if you find any problems.

**Comment by satishtiwari23** [comment]
Thanks! @zeerorg!
It is working now.
