### ISSUE TITLE
Move to connector-sdk

### ISSUE THREAD

**Issue by alexellis** [zeerorg/cron-connector#3]
Hi, it'd be great if you could move to use the latest version of the connector-sdk

https://github.com/openfaas-incubator/connector-sdk/

See the example for how to do that. It prevents duplication for one thing.

Once done, let me know so we can test it out and potentially list as a connector in the OpenFaaS docs.

Alex

**Comment by zeerorg** [comment]
Moved to connector sdk version 0.3.1 https://github.com/zeerorg/cron-connector/commit/1a57b6250b84f6ff7ce1a65d8ef33ae12dfe67fa
